=== search-cloud/spring-boot-cloud-microservices-docker/asion-account/asion-account-core/src/test/resources/database/xsd/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="asion_account">
	<xsd:import namespace="asion_account" schemaLocation="asion_account.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="asion_account" type="dflt:asion_account__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:any namespace="asion_account" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== search-cloud/spring-boot-cloud-microservices-docker/asion-account/asion-account-core/src/test/resources/database/dataset/asion_account.xml
<?xml version='1.0' encoding='utf-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/dataset.xsd">

	<asion_account id="1" code="This is the test text1!" username="Summary1" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="2" code="This is the test text2" username="Summary2" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="3" code="This is the test text3" username="Summary3" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="4" code="This is the test text4" username="Summary4" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="5" code="This is the test text5" username="Summary5" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="6" code="This is the test text6" username="Summary6" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="7" code="This is the test text7" username="Summary7" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="8" code="This is the test text8" username="Summary8" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="9" code="This is the test text9" username="Summary9" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="10" code="This is the test text10" username="Summary10" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="11" code="This is the test text11" username="Summary11" created_at="2016-05-01" updated_at="2016-05-01"/>
	<asion_account id="12" code="This is the test text12" username="Summary12" created_at="2016-05-01" updated_at="2016-05-01"/>

</dataset>
